baseURL: https://www.daehli.no/
languageCode: en-us
title: Morten Dæhli Aslesen
theme: ghostwriter
copyright: Morten Dæhli Aslesen
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Morten Dæhli Aslesen
  profile: "👋 Hi, I’m Morten Dæhli Aslesen, and I'm currently working as an IT-consultant at Bouvet Norway ASA"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Morten Dæhli Aslesen
  description: 👋 Welcome to my tech tinkering blog!
  github: "https://github.com/mortedaehli/"
  linkedin: "https://www.linkedin.com/in/morten-d%C3%A6hli-aslesen-50765164/"
  facebook: "https://www.facebook.com/morten.aslesen/"
  email: post@daehli.no
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Projects
      url: /project/
      weight: 2
    - name: Contact
      url: /page/contact/
      weight: 3
    - name: About
      url: /page/about/
      weight: 4
